### ISSUE TITLE
Feature: User can search for games

### ISSUE THREAD

**Issue by hqpham98** [hqpham98/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for a game amongst a database of known games.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user is presented with a home page with a search bar that will use the input as a search query to grab game information from a game database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="934" alt="image" src="https://github.com/hqpham98/ajax-project/assets/7689363/0c19653b-5c80-444c-bc48-9114d40c92fd">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a NavBar with a Home Page and Catalog button.
- [x] Add a title to the body of the page.
- [x] Add a search bar to the center of the page
- [x] Add an event listener to the search bar to listen for input events to build the search query for the API.
- [x] Add an event listener to the form to listen for a submit event.
  - [x] Pull search results from API and store locally.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
