### ISSUE TITLE
Feature: User can view live results for search queries

### ISSUE THREAD

**Issue by hqpham98** [hqpham98/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can type in game names into the search bar and live results will appear below the search bar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Users can see live results for the game name they are typing out in real time.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1089" alt="image" src="https://github.com/hqpham98/ajax-project/assets/7689363/647628a8-e1c7-45f5-9fe5-771434f392f9">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When there is user input, create a delay of 1 second before a search is queried.
- [x] Create a floating results popup when there is user input in the search bar
- [x] Create event listener for focus event for the search bar.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
