### ISSUE TITLE
Feature: User can view specific game information

### ISSUE THREAD

**Issue by hqpham98** [hqpham98/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1229" alt="image" src="https://github.com/hqpham98/ajax-project/assets/7689363/f827ff6c-6a60-4dd1-b09a-90e0c2be8ec7">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Store game search result in local storage from index.html.
- [x] Create new game.html for game page.
- [x] Add event listener to game results entries to open the new html.
- [x] Create rows and columns for formatting the game title, rating, platforms, release date, about, game image, etc.
- [x] Add nav bar.
- [x] Add search bar.
- [x] Pull game data and format it.
- [x] Add background with a transparent game image.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
